import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getAdminId } from "@/lib/auth";
import { slugify } from "@/lib/slug";
import { sanitizeHtml } from "@/lib/html";

export async function PUT(req:Request,{params}:{params:Promise<{id:string}>}){if(!(await getAdminId()))return NextResponse.json({error:"Unauthorized"},{status:401});const{id}=await params;const idNum=Number(id);if(!Number.isInteger(idNum))return NextResponse.json({error:"Invalid drama id."},{status:400});const b=await req.json().catch(()=>null);const title=String(b?.title||"").trim();if(!title)return NextResponse.json({error:"Title is required."},{status:400});let slug=slugify(String(b?.slug||title));const conflict=await prisma.drama.findFirst({where:{slug,NOT:{id:idNum}}});if(conflict)return NextResponse.json({error:"Slug already exists."},{status:409});const genreIdNum=Number(b?.genreId);const genreId=(b?.genreId&&Number.isFinite(genreIdNum))?genreIdNum:null;try{const d=await prisma.drama.update({where:{id:idNum},data:{title,slug,description:sanitizeHtml(String(b?.description||"")),posterUrl:String(b?.posterUrl||"")||null,bannerUrl:String(b?.bannerUrl||"")||null,genreId,status:b?.status==="PUBLISHED"?"PUBLISHED":"DRAFT",featured:Boolean(b?.featured)}});return NextResponse.json({id:d.id})}catch(err:any){if(err?.code==="P2025")return NextResponse.json({error:"Drama not found."},{status:404});if(err?.code==="P2003")return NextResponse.json({error:"That genre doesn't exist."},{status:400});return NextResponse.json({error:"Update failed."},{status:500})}}

export async function DELETE(_req:Request,{params}:{params:Promise<{id:string}>}){if(!(await getAdminId()))return NextResponse.json({error:"Unauthorized"},{status:401});const{id}=await params;const idNum=Number(id);if(!Number.isInteger(idNum))return NextResponse.json({error:"Invalid drama id."},{status:400});const d=await prisma.drama.delete({where:{id:idNum}}).catch(()=>null);if(!d)return NextResponse.json({error:"Drama not found."},{status:404});return NextResponse.json({ok:true})}
